package org.example;

import jakarta.persistence.*;

/**
 * LlamadasEmitidas generated by hbm2java
 */
@Entity
@Table(name = "LLAMADAS_EMITIDAS") // nombre exacto de la tabla en la BD
public class LlamadasEmitida implements java.io.Serializable {

    @Id
    @Column(name = "CODIGO_LLAMADA") // nombre exacto de la columna en la BD
    private int codigoLlamada;

    @Column(name = "NUMERO_LLAMADO")
    private int numeroLlamado;

    @Column(name = "DURACION_LLAMADA")
    private int duracionLlamada;

    @Column(name = "IMPORTE_LLAMADA")
    private float importeLlamada;

    public LlamadasEmitida() {}

    public LlamadasEmitida(int codigoLlamada, int numeroLlamado,
                           int duracionLlamada, float importeLlamada) {
        this.codigoLlamada = codigoLlamada;
        this.numeroLlamado = numeroLlamado;
        this.duracionLlamada = duracionLlamada;
        this.importeLlamada = importeLlamada;
    }

    // Getters y Setters
    public int getCodigoLlamada() { return this.codigoLlamada; }
    public void setCodigoLlamada(int codigoLlamada) { this.codigoLlamada = codigoLlamada; }

    public int getNumeroLlamado() { return this.numeroLlamado; }
    public void setNumeroLlamado(int numeroLlamado) { this.numeroLlamado = numeroLlamado; }

    public int getDuracionLlamada() { return this.duracionLlamada; }
    public void setDuracionLlamada(int duracionLlamada) { this.duracionLlamada = duracionLlamada; }

    public float getImporteLlamada() { return this.importeLlamada; }
    public void setImporteLlamada(float importeLlamada) { this.importeLlamada = importeLlamada; }
}